name: "GitHub Actions"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build image with Vagrant
      run: |
        sudo apt install -y vagrant virtualbox && \
        vagrant up
