name: "GitHub Actions"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build image with Vagrant
        run: vagrant up
      - name: Package box for Vagrant Cloud
        run: vagrant package --base pentesting-vm
