name: packer

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: packer validate -syntax-only .
      - run: packer build -color=false -on-error=abort .
        env:
          PACKER_LOG: 1

